### ISSUE TITLE
.numbers with password

### ISSUE THREAD

**Issue by guilhermeasena32** [masaccio/numbers-parser#88] opened 2024-06-20 23:43 UTC
I am working with some .numbers files and one of them is password-protected. How can I parse this file by providing the password? Is it possible?

**Comment by masaccio** [comment] 2024-06-21 11:03
Documents are AES-128 encrypted if we believe the Internet, which means we need the private key. I can see that there is an entry in the Mac Keychain for the password, but export is greyed out. However it can be found on the command-line:

``` bash
security find-generic-password -w -g -D "iWork Document Password (Encrypted)"
```

But this generates a 290 byte 'password' or key which I don't know what it is yet.

So if we can determine how the data is encrypted, it is pretty straightforward then to decrypt with a key from the Keychain.

**Comment by guilhermeasena32** [comment] 2024-06-21 11:58
I know the password, but libreoffice cannot open these files with password because it considers corrupted and I have not found any solution to provide the password to parse the file.

**Comment by masaccio** [comment] 2024-06-21 12:40
The problem is that I am struggling to figure out how it's encrypted at the moment so unless I have a breakthrough, it's blocked.

**Comment by guilhermeasena32** [comment] 2024-06-21 14:59
no problem, thanks @masaccio

**Comment by masaccio** [comment] 2024-06-29 13:46
Closing as won't fix as it seems very unlikely the encryption format will be discovered. [Docs updated to reflect this.](https://github.com/masaccio/numbers-parser?tab=readme-ov-file#limitations)

**Closed by masaccio** 2024-06-29 13:46 UTC
